version: '3.8'

services:

  traefik:
    image: traefik:v2.10
    command:
      - --providers.file.filename=/traefik/dynamic_conf.yml
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --api.dashboard=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/dynamic_conf.yml:/traefik/dynamic_conf.yml
    deploy:
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: containous/whoami
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.entrypoints=web"
      placement:
        constraints:
          - node.role == manager

  scheduler:
    image: scheduler:1.0
    working_dir: /app
    command: ["python", "main.py"]
    ports:
      - "8000:8000"
    depends_on:
      - traefik
    deploy:
      placement:
        constraints:
          - node.role == manager

  flask-node-api:
    image: 211.183.4.128:5000/flask-node-api:1.0
    container_name: flask-node-api
    working_dir: /app
    ports:
      - "5000:5000"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
